### ISSUE TITLE
`Github Actions` extension in `VS Code` gives warning on use of `args`

### ISSUE THREAD

**Issue by vegar** [equinor/radix-github-actions#31]
VS Code v1.84.2
GitHub Actions  v0.26.2

The validation routines in the github actions extension shows error on `args`. 
Not sure why, but it's anoying, so if there is something that can be done in the implmentation of the action to make it understand it's totally fine, it would be great :-)

![image](https://github.com/equinor/radix-github-actions/assets/764517/effb27ec-23d7-44bf-8401-0ca87ebbea9c)

**Comment by nilsgstrabo** [comment]
We have just released a fix for this.
